import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'markdown-combiner',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja' className='dark'>
      {' '}
      <body className={`${inter.className} flex flex-col min-h-screen bg-gray-900 text-white m-0`}>
        {' '}
        {/* Updated background and text colors for dark theme */}
        {children}
      </body>
    </html>
  );
}
